# config.yaml

seed: 42
# configs/config.yaml
seed: 42
dataset_root: "/content/drive/MyDrive/Brain-Tumor-ClassificationV/briscDataset"
image_size: 224
batch_size: 16
num_workers: 2


model:

  - name: resnet50
    n_unfreeze: 1
    batch_size: 16
    epochs: 10
    lr: 0.0001

  - name: resnet50_n2
    model: resnet50
    n_unfreeze: 2
    batch_size: 16
    epochs: 10
    lr: 0.0001

  - name: densenet121
    n_unfreeze: 2
    batch_size: 16
    epochs: 10
    lr: 0.0001

  - name: dino
    model: dino
    n_unfreeze: 2
    batch_size: 8
    epochs: 20
    lr: 0.00005
