# config.yaml

seed: 42

dataset:
  train_path: /content/train
  test_path: /content/test
  image_size: 224
  num_workers: 2

experiments:

  - name: resnet50_n1
    model: resnet50
    n_unfreeze: 1
    batch_size: 16
    epochs: 10
    lr: 0.0001

  - name: resnet50_n2
    model: resnet50
    n_unfreeze: 2
    batch_size: 16
    epochs: 10
    lr: 0.0001

  - name: densenet121_n2
    model: densenet121
    n_unfreeze: 2
    batch_size: 16
    epochs: 10
    lr: 0.0001

  - name: dino_n2
    model: dino
    n_unfreeze: 2
    batch_size: 8
    epochs: 20
    lr: 0.00005
